DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(20),
  remarks VARCHAR(300)
);
CREATE SEQUENCE users_seq START 1;

insert into users values(1,'田中 実'),
(2,'鈴木 茂'),
(3,'鈴木 実'),
(4,'佐藤 清'),
(5,'高橋 清'),
(6,'佐藤 正'),
(7,'佐藤 進'),
(8,'鈴木 清'),
(9,'田中 稔'),
(10,'鈴木 博'),
(11,'鈴木 花子'),
(12,'田中 優子'),
(13,'鈴木 友美');